# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('date_sign_up', models.DateField()),
                ('gross_sale', models.FloatField()),
                ('cash_recieved', models.FloatField()),
                ('eft_added', models.FloatField()),
                ('eft_loss', models.FloatField()),
                ('date_input', models.DateField(default=django.utils.timezone.now)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
                ('note3', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.ManyToManyField(to='client.Lead'),
        ),
        migrations.AddField(
            model_name='client',
            name='program_sold',
            field=models.ManyToManyField(to='client.Program'),
        ),
        migrations.AddField(
            model_name='client',
            name='sold_by',
            field=models.ManyToManyField(to='client.Trainer'),
        ),
    ]
