# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lead_source',
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.OneToOneField(default="0", on_delete=django.db.models.deletion.CASCADE, to='client.Lead'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='program_sold',
        ),
        migrations.AddField(
            model_name='client',
            name='program_sold',
            field=models.OneToOneField(default="0", on_delete=django.db.models.deletion.CASCADE, to='client.Program'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='sold_by',
        ),
        migrations.AddField(
            model_name='client',
            name='sold_by',
            field=models.OneToOneField(default="0", on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
            preserve_default=False,
        ),
    ]
