# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160624_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_sale', models.FloatField()),
                ('cash_recieved', models.FloatField()),
                ('eft_added', models.FloatField()),
                ('eft_loss', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 6, 25, 3, 18, 4, 456523, tzinfo=utc))),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
                ('note3', models.TextField(blank=True)),
                ('sold_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Trainer')),
            ],
        ),
    ]
