# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sold_by',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default="0"),
        ),
    ]
