# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20160625_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sold_by',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
