# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20160625_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Lead'),
        ),
        migrations.AlterField(
            model_name='client',
            name='program_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Program'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
        ),
    ]
