# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20160625_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_sign_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
