# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0008_auto_20160625_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consultation_scheduled', models.IntegerField()),
                ('consultation_showed', models.IntegerField()),
                ('consultation_closed', models.IntegerField()),
                ('consult_no_call_no_show', models.IntegerField()),
                ('consult_cancelled_rescheduled', models.IntegerField()),
                ('consult_cancelled', models.IntegerField()),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Trainer')),
            ],
        ),
    ]
