# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='consult_cancelled',
            new_name='consultations_cancelled',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='consult_cancelled_rescheduled',
            new_name='consultations_closed',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='consult_no_call_no_show',
            new_name='consultations_no_show',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='consultation_closed',
            new_name='consultations_rescheduled',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='consultation_scheduled',
            new_name='consultations_scheduled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='consultation_showed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sold_by',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultations_requested',
            field=models.IntegerField(default=1),
        ),
    ]
