# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20160704_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultations_requested',
            field=models.IntegerField(),
        ),
    ]
