# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20160707_1830'),
        ('appointment', '0003_auto_20160704_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='input_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='note1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
