# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20160711_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultations_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='input_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
        ),
    ]
