# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20160711_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultations_attended',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='input_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
        ),
    ]
