# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20160625_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sold_by',
        ),
    ]
