# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160624_1121'),
        ('sales', '0003_remove_record_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sold_by',
            field=models.OneToOneField(default="0", on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default="0"),
        ),
    ]
