# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20160625_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default="0"),
        ),
    ]
