# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20160625_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 25, 5, 5, 29, 724960, tzinfo=utc)),
        ),
    ]
