# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20160704_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='consults_attended',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='consults_closed',
            field=models.FloatField(),
        ),
    ]
