# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20160707_1830'),
        ('sales', '0015_auto_20160707_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='note3',
        ),
        migrations.AddField(
            model_name='record',
            name='sold_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
        ),
    ]
