# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20160711_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='consults_attended',
        ),
        migrations.RemoveField(
            model_name='record',
            name='consults_closed',
        ),
        migrations.AlterField(
            model_name='record',
            name='sold_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='client.Trainer'),
        ),
    ]
